# Generated by Django 3.0.5 on 2020-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_massage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='T_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='Pan_no',
            field=models.CharField(default='PAN', max_length=20),
        ),
    ]
