# Generated by Django 3.0.5 on 2020-09-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_donationmade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
