# Generated by Django 3.0.5 on 2020-09-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20200922_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='orderid',
            field=models.IntegerField(default=1),
        ),
    ]
