# Generated by Django 3.0.5 on 2020-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_donation_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmade',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
    ]
