# Generated by Django 3.0.5 on 2020-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_donationmade_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='donationmade',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=30),
        ),
    ]
